from enum import StrEnum


class QuotaStatus(StrEnum):
    NEW = "NEW"
    AVAILABLE = "AVAILABLE"
    SEEN = "SEEN"
    RESERVED = "RESERVED"
    SOLD = "SOLD"
    REMOVED = "REMOVED"
    UNAVAILABLE = "UNAVAILABLE"
    SILENCED = "SILENCED"
    UNKNOWN = "UNKNOWN"


class InconsistencyLevel(StrEnum):
    CONSISTENT = "CONSISTENTE"
    REVIEW = "REVISAR"
    CRITICAL = "INCONSISTENTE_EXIGIR_EXTRATO"
    NOT_APPLICABLE = "NAO_APLICAVEL"


class ConfidenceLevel(StrEnum):
    HIGH = "alta"
    MEDIUM = "média"
    LOW = "baixa"


class CreditCalculationStatus(StrEnum):
    LIQUID = "LIQUIDO"
    UPDATED = "ATUALIZADO"
    NOMINAL_FALLBACK = "PROVISORIO_NOMINAL"
    UNAVAILABLE = "INDISPONIVEL"


class OpportunityClass(StrEnum):
    GOLD = "OURO"
    EXCEPTIONAL = "EXCEPCIONAL"
    VERY_GOOD = "MUITO_BOA"
    GOOD = "BOA"
    NORMAL = "NORMAL"
    NO_PRICE = "SEM_PRECO"
    INVALID_DATA = "DADO_INVALIDO"


class CombinationRuleStatus(StrEnum):
    CONFIRMED = "CONFIRMADA"
    NOT_ALLOWED = "NAO_PERMITIDA"
    POTENTIAL = "POTENCIAL_REGRA_A_CONFIRMAR"
    UNKNOWN = "DESCONHECIDA"


class RegulationValidationStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PENDING_MANUAL_VALIDATION = "PENDING_MANUAL_VALIDATION"
    NOT_ALLOWED = "NOT_ALLOWED"


class AdapterAccessBlockReason(StrEnum):
    CAPTCHA = "CAPTCHA"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    TECHNICAL_BLOCK = "BLOQUEIO_TECNICO"
    TIMEOUT = "TIMEOUT"
    HTTP_ERROR = "ERRO_HTTP"
    CONTENT_UNAVAILABLE = "CONTEUDO_INACESSIVEL"
    STOCK_NOT_RENDERED = "ESTOQUE_NAO_RENDERIZADO"
    MANUAL_INTERVENTION_REQUIRED = "INTERVENCAO_MANUAL_NECESSARIA"
    SESSION_EXPIRED = "SESSAO_EXPIRADA"
